pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - author=rrbugproof
      - "#approved-reviews-by >= 1"
    actions:
      merge:
